// Content audit, phase 6: adds a "Sources" section with verified big-outlet links. Every URL below was
// returned by a live search of that outlet during the audit. Run from the repo root.
import { readFileSync, writeFileSync } from 'node:fs';

const TC = 'https://techcrunch.com/', CNBC = 'https://www.cnbc.com/', ENG = 'https://www.engadget.com/', G9 = 'https://9to5google.com/';
const S = {
  astra: ['CNBC: OpenAI announces rollout of GPT-6 Astra model', CNBC + '2026/09/03/open-ai-astra-gpt-6-cyber.html'],
  astraTc: ['TechCrunch: OpenAI launches Astra, its powerful (and controversial) new model', TC + '2026/09/03/openai-launches-astra-its-powerful-and-controversial-new-model/'],
  astraEng: ['Engadget: OpenAI says GPT-6 Astra is "the most intelligent and aligned model in the world"', ENG + '2250814/openai-says-gpt-6-astra-is-the-most-intelligent-and-aligned-model-in-the-world/'],
  solLuna: ['TechCrunch: OpenAI launches GPT-6 Sol and Luna, boasting lower cost and fewer mistakes', TC + '2026/09/22/openai-launches-gpt-6-sol-and-luna/'],
  chatgptFree: ['Engadget: ChatGPT, what is free in 2026 and what is not', ENG + '2234173/chatgpt-free-features-2026/'],
  chatgptWork: ['Engadget: OpenAI releases a new ChatGPT tool for all things work related', ENG + '2211869/openai-releases-chatgpt-work-tool-macos-windows-web-plans/'],
  schedFree: ['Engadget: Free accounts can now access ChatGPT’s upgraded task scheduling tool', ENG + '2244194/free-accounts-can-now-access-chatgpts-upgraded-task-scheduling-tool/'],
  schedHub: ['Engadget: ChatGPT now has a hub for scheduled tasks', ENG + '2196844/chatgpt-now-has-a-hub-for-scheduled-tasks/'],
  schedTc: ['TechCrunch: ChatGPT now lets you schedule reminders and recurring tasks', TC + '2025/01/14/chatgpt-now-lets-you-schedule-reminders-and-recurring-tasks/'],
  dsV4: ['CNBC: China’s DeepSeek releases preview of long-awaited V4 model as AI race intensifies', CNBC + '2026/04/24/deepseek-v4-llm-preview-open-source-ai-competition-china.html'],
  son5: ['TechCrunch: Anthropic launches Claude Sonnet 5 as a cheaper way to run agents', TC + '2026/06/30/anthropic-launches-claude-sonnet-5-as-a-cheaper-way-to-run-agents/'],
  son55: ['TechCrunch: Anthropic releases Sonnet 5.5, a significantly cheaper, faster work partner', TC + '2026/09/28/anthropic-releases-sonnet-5-5-which-it-calls-a-significantly-cheaper-faster-work-partner/'],
  son5Eng: ['Engadget: Anthropic’s new Sonnet 5 model is better at the tasks that are running up enterprise bills', ENG + '2205475/anthropic-releases-claude-sonnet-5-model/'],
  ccAuto: ['TechCrunch: Anthropic is turning Claude Code’s auto mode on by default', TC + '2026/08/09/anthropic-is-turning-claude-codes-auto-mode-on-by-default/'],
  ccEng: ['Engadget: Anthropic releases safer Claude Code auto mode', ENG + 'ai/anthropic-releases-safer-claude-code-auto-mode-to-avoid-mass-file-deletions-and-other-ai-snafus-142500615.html'],
  ccLeash: ['TechCrunch: Anthropic hands Claude Code more control, but keeps it on a leash', TC + '2026/03/24/anthropic-hands-claude-code-more-control-but-keeps-it-on-a-leash/'],
  curRev: ['TechCrunch: Cursor has reportedly surpassed $2B in annualized revenue', TC + '2026/03/02/cursor-has-reportedly-surpassed-2b-in-annualized-revenue/'],
  curSpace: ['CNBC: SpaceX to acquire the AI coding startup Cursor for $60 billion', CNBC + '2026/06/16/spacex-spcx-cursor-acquisition-ipo.html'],
  curUpd: ['CNBC: Cursor announces major update to AI agents as coding tool battle heats up', CNBC + '2026/02/24/cursor-announces-major-update-as-ai-coding-agent-battle-heats-up.html'],
  ghOut: ['CNBC: Microsoft’s GitHub was positioned to win the AI coding race, but outages got in the way', CNBC + '2026/05/22/microsoft-was-positioned-to-win-in-ai-coding-outages-got-in-the-way.html'],
  molCnbc: ['CNBC: Meta gets into social networks for AI agents with acquisition of viral Moltbook platform', CNBC + '2026/03/10/meta-social-networks-ai-agents-moltbook-acquisition.html'],
  molTc: ['TechCrunch: Meta acquired Moltbook, the AI agent social network that went viral because of fake posts', TC + '2026/03/10/meta-acquired-moltbook-the-ai-agent-social-network-that-went-viral-because-of-fake-posts/'],
  molEng: ['Engadget: Meta is buying Moltbook, the ridiculous social network populated by AI bots', ENG + 'ai/meta-is-buying-moltbook-the-ridiculous-social-network-populated-by-ai-bots-152732453.html'],
  movVar: ['Variety: Artificial trailer, Andrew Garfield is Sam Altman as Neon sets Christmas Day release', 'https://variety.com/2026/film/news/artificial-trailer-andrew-garfield-openai-biopic-1236802616/'],
  movDead: ['Deadline: Artificial teaser trailer shows Andrew Garfield as Sam Altman', 'https://deadline.com/2026/09/artificial-trailer-andrew-garfield-luca-guadagnino-1237070971/'],
  movEng: ['Engadget: The first trailer for the Sam Altman biopic is damn creepy', ENG + '2253048/the-first-trailer-for-the-sam-altman-biopic-is-damn-creepy/'],
  eduKhan: ['CNBC: Microsoft, Khan Academy provide free AI assistant for all educators in US', CNBC + '2024/05/21/microsoft-khan-academy-launch-free-ai-assistant-for-all-us-teachers.html'],
  eduGoogle: ['TechCrunch: Google adds Gemini to its Education suite', TC + '2024/05/16/google-adds-gemini-to-its-education-suite/'],
  eduPop: ['CNBC: AI is getting very popular among students and teachers, very quickly', CNBC + '2024/06/11/ai-is-getting-very-popular-among-students-and-teachers-very-quickly.html'],
  stuEng: ['Engadget: Google is offering college students a year of its AI Pro plan for free', ENG + '2240161/google-is-offering-college-students-a-year-of-ai-pro-for-free/'],
  stuNb: ['9to5Google: Gemini Live adds Deep Research as Notebooks come to AI Mode', G9 + '2026/08/19/gemini-app-ai-mode-study-tools/'],
  pplxPc: ['TechCrunch: Perplexity’s Personal Computer is now available to everyone on Mac', TC + '2026/05/07/perplexitys-personal-computer-is-now-available-everyone-on-mac/'],
  pplxHyb: ['Engadget: Perplexity’s Hybrid Compute splits sensitive tasks between cloud and local AI', ENG + '2248548/perplexitys-hybrid-compute-splits-sensitive-tasks-between-cloud-and-local-ai/'],
  pplxComet: ['TechCrunch: Perplexity’s Comet AI browser now free', TC + '2025/10/02/perplexitys-comet-ai-browser-now-free-max-users-get-new-background-assistant/'],
  cop20: ['TechCrunch: Microsoft says it has over 20M paid Copilot users', TC + '2026/04/29/microsoft-says-it-has-over-20m-paid-copilot-users-and-they-really-are-using-it/'],
  copApp: ['Engadget: Microsoft’s Copilot app adds Office, natural coding and automation', ENG + '2268096/microsofts-copilot-app-adds-office-natural-coding-and-automation/'],
  rtxLimbo: ['Tom’s Hardware: Nvidia RTX 50 Super GPUs are reportedly stuck in limbo due to GDDR7 pricing', 'https://www.tomshardware.com/pc-components/gpus/nvidia-rtx-50-super-gpus-are-reportedly-ready-but-stuck-in-limbo-due-to-excessive-gddr7-pricing-3gb-gddr7-module-costs-triple-the-price-of-2gb'],
  qwen: ['Tom’s Hardware: Benchmarking Qwen 3.8 27B on RTX 5090 and beyond', 'https://www.tomshardware.com/tech-industry/artificial-intelligence/benchmarking-qwen-3-8-27b-on-rtx-5090-and-beyond-vram-capacity-alone-cant-overcome-severe-software-and-inference-engine-bottlenecks'],
  gtaPc: ['PC Gamer: When might the GTA 6 PC release date be?', 'https://www.pcgamer.com/games/grand-theft-auto/gta-6-pc-release-date/'],
  gtaHub: ['PC Gamer: Grand Theft Auto 6 coverage', 'https://www.pcgamer.com/grand-theft-auto-6/'],
  dfCall: ['TechCrunch: Google rolls out fake call detection to protect against AI deepfake impersonation scams', TC + '2026/06/02/google-rolls-out-fake-call-detection-to-protect-against-ai-deepfake-impersonation-scams/'],
  dfBleep: ['BleepingComputer: Google adds Android protection against AI deepfake scam calls', 'https://www.bleepingcomputer.com/news/security/google-adds-android-protection-against-ai-deepfake-scam-calls/'],
  optCnbc: ['CNBC: Don’t want chatbots using your conversations for AI training? Some let you opt out', CNBC + '2024/08/16/ai-training-chatgpt-google-meta-grok-claude.html'],
  optEng: ['Engadget: How to stop AI companies from training on your data', ENG + '2268598/how-to-stop-ai-companies-training-your-data/'],
  optTc: ['TechCrunch: Anthropic users face a new choice, opt out or share your data for AI training', TC + '2025/08/28/anthropic-users-face-a-new-choice-opt-out-or-share-your-data-for-ai-training/'],
  nanoIn: ['TechCrunch: India leads the way on Google’s Nano Banana with a local creative twist', TC + '2025/09/17/india-leads-the-way-on-googles-nano-banana-with-a-local-creative-twist/'],
  nano9: ['9to5Google: Nano Banana responsible for 10+ million first-time Gemini app users', G9 + '2025/09/04/gemini-app-nano-banana/'],
  nanoCnbc: ['CNBC: Google’s Gemini tops Apple’s App Store, snagging lead spot from ChatGPT', CNBC + '2025/09/16/google-gemini-tops-apples-app-store-snagging-lead-spot-from-chatgpt.html'],
  img25: ['TechCrunch: ChatGPT can now virtually try on clothes for you', TC + '2026/10/01/chatgpt-can-now-virtually-try-on-clothes-for-you/'],
  imgEng: ['Engadget: ChatGPT image generation is now faster and better at following tweaks', ENG + 'ai/chatgpt-image-generation-is-now-faster-and-better-at-following-tweaks-180000750.html'],
  grokTc: ['TechCrunch: Grok Imagine, xAI’s new AI image and video generator', TC + '2025/08/04/grok-imagine-xais-new-ai-image-and-video-generator-lets-you-make-nsfw-content/'],
  grokCnbc: ['CNBC: Musk’s X faces probes in Europe, India, Malaysia after Grok generated explicit images', CNBC + '2026/01/05/india-eu-investigate-musks-x-after-grok-created-deepfake-child-porn.html'],
  soraWhy: ['TechCrunch: Why OpenAI really shut down Sora', TC + '2026/03/29/why-openai-really-shut-down-sora/'],
  soraCnbc: ['CNBC: OpenAI shutters short-form video app Sora as company reels in costs', CNBC + '2026/03/24/openai-shutters-short-form-video-app-sora-as-company-reels-in-costs.html'],
  omni: ['TechCrunch: Google’s Gemini Omni turns images, audio, and text into video', TC + '2026/05/19/googles-gemini-omni-turns-images-audio-and-text-into-video-and-thats-just-the-start/'],
  flowApps: ['9to5Google: Google Flow AI video editing and music tools getting dedicated apps and Omni upgrades', G9 + '2026/05/19/google-flow-video-music-ai-apps/'],
  el4: ['TechCrunch: ElevenLabs’ new v4 speech model supports more expression control and 90 languages', TC + '2026/09/28/elevenlabs-new-v4-speech-model-supports-more-expression-control-and-90-languages/'],
  nvPc: ['PC Gamer: Latest Nvidia Game Ready drivers fix various black screen issues', 'https://www.pcgamer.com/hardware/graphics-cards/latest-nvidia-game-ready-drivers-fix-various-black-screen-issues-that-left-gamers-staring-at-their-sad-reflections/'],
  nvTom: ['Tom’s Hardware: Nvidia hotfix arrives to address remaining black screen issues', 'https://www.tomshardware.com/pc-components/gpu-drivers/nvidia-hotfix-arrives-to-address-black-screen-issues-remaining-after-thursdays-driver-release'],
  googleGenAi: ['Google Search Central: Using generative AI content on your website', 'https://developers.google.com/search/docs/fundamentals/using-gen-ai-content'],
};

const MAP = {
  'gpt-6-astra-release': ['astra', 'astraTc', 'astraEng'],
  'what-does-gpt-stand-for': ['solLuna', 'astraTc'],
  'how-to-use-chatgpt-effectively': ['chatgptFree', 'solLuna'],
  'best-chatgpt-prompts-2026': ['chatgptWork', 'solLuna'],
  'chatgpt-prompts-for-business-strategy': ['chatgptWork', 'astraTc'],
  'chatgpt-free-automations-guide': ['schedFree', 'schedHub', 'schedTc'],
  'deepseek-v4-vs-chatgpt-comparison': ['dsV4', 'solLuna'],
  'deepseek-ai-2026-review': ['dsV4'],
  'claude-sonnet-5-release': ['son5', 'son55', 'son5Eng'],
  'claude-code-cli-tutorial': ['ccAuto', 'ccEng', 'ccLeash'],
  'cursor-ai-review-2026': ['curRev', 'curSpace', 'curUpd'],
  'blackbox-ai': ['curUpd', 'ghOut'],
  'moltbook-ai-agent-platform-social-network': ['molCnbc', 'molTc', 'molEng'],
  'artificial-movie-andrew-garfield-sam-altman': ['movVar', 'movDead', 'movEng'],
  'ai-for-education-2026': ['eduKhan', 'eduGoogle', 'eduPop'],
  'google-gemini-pro-students': ['stuEng', 'stuNb'],
  'google-ai-plus-for-students': ['stuEng', 'stuNb'],
  'how-to-use-notebooklm': ['stuNb'],
  'perplexity-pro-vs-chatgpt-plus-2026': ['pplxPc', 'pplxHyb'],
  'perplexity-for-students-2026': ['pplxComet'],
  'copilot-excel-hacks': ['cop20', 'copApp'],
  'best-gaming-pc-ai-and-gaming-2026': ['rtxLimbo', 'qwen'],
  'gta-6-system-requirements': ['gtaPc', 'gtaHub'],
  'how-to-detect-deepfakes-guide': ['dfCall', 'dfBleep'],
  'how-to-protect-your-data-from-ai-chatbots': ['optCnbc', 'optEng', 'optTc'],
  'best-vpn-for-ai-browsing': ['optEng', 'optCnbc'],
  '3d-figurine-ai-trend-chatgpt': ['nanoIn', 'nano9', 'nanoCnbc'],
  '90s-ai-photo-trend-gemini-prompt': ['nanoIn', 'nano9'],
  'chatgpt-image-prompts-visual-commands': ['img25', 'imgEng'],
  'grok-imagine-2-0-prompts-guide': ['grokTc', 'grokCnbc'],
  'best-ai-image-generators-2026': ['img25'],
  'best-ai-video-generators-of-2026': ['soraWhy', 'soraCnbc', 'omni'],
  'artificial-intelligence-tools-2026': ['soraWhy', 'el4', 'omni'],
  'google-flow-camera-commands': ['omni', 'flowApps'],
  'how-to-use-ai-voice-generators': ['el4'],
  'fix-nvidia-driver-crashing-2026': ['nvPc', 'nvTom'],
  'how-to-humanize-ai-content-guide': ['googleGenAi'],
};

for (const [slug, keys] of Object.entries(MAP)) {
  const path = `src/content/blog/${slug}.md`;
  let t = readFileSync(path, 'utf8').replaceAll('\r\n', '\n');
  if (/^## Sources$/m.test(t)) { console.log('skip (has Sources):', slug); continue; }
  const bullets = keys.filter(k => !t.includes(`(${S[k][1]})`)).map(k => `- [${S[k][0]}](${S[k][1]})`);
  if (!bullets.length) continue;
  const block = `## Sources\n\n${bullets.join('\n')}\n\n`;
  t = t.includes('\n## Related Reading') ? t.replace('\n## Related Reading', `\n${block}## Related Reading`) : t.trimEnd() + '\n\n' + block;
  writeFileSync(path, t);
}
